[profile.default]
src = 'src'
test = 'test'
out = 'out/foundry'
cache_path = 'out/foundry-cache'
broadcast = 'out/foundry-broadcast'
fs_permissions = [{ access = "write", path = "./out/"}]
allow_paths= ['../../node_modules']
remappings= [
  '@openzeppelin/=../../node_modules/@openzeppelin/',
  'forge-std/=../../node_modules/forge-std/src/',
  'ds-test/=../../node_modules/ds-test/src/',
  'diamond/=../../node_modules/diamond/'
]

[profile.doc]
out = 'out/docs'
# repository = fixme add public contracts repo